package game

// Hand-fixed translations of procedures the translator cannot handle.

// finalScene  (1e9b:734a)
// finalScene gets the flag (var parameter in the original) telling whether
// the principal's trapdoor button was disabled.
func (g *Game) finalScene(buttonBroken int) {
	g.clearMenuWin()
	g.resetViewPort()
	g.showRoomPic("suli261.pic")
	g.OutTextXY(310, 170, "Szélesre tárod az ajtót, és belépsz.")
	g.OutTextXY(310, 185, "Egy hatalmas íróasztal mögött Kolompai")
	g.OutTextXY(310, 200, "Edömér ül odabenn.")
	g.OutTextXY(310, 215, "- Eljöttem! - kiáltod, és teátrális")
	g.OutTextXY(310, 230, "mozdulattal berántod a motorfürészt.")
	g.OutTextXY(310, 245, "- Látom. - feleli Kolompai, és")
	g.OutTextXY(310, 260, "gúnyos nevetéssel lenyom egy fekete")
	g.OutTextXY(310, 275, "gombot az íróasztala szélén.")
	if buttonBroken == 0 {
		g.OutTextXY(310, 290, "Abban a pillanatban megnyílik alattad")
		g.OutTextXY(310, 305, "egy süllyesztö, és a mélybe zuhansz.")
		g.OutTextXY(310, 320, "Tizenöt méterrel lejjebb egy sor")
		g.OutTextXY(310, 335, "hegyes karó vet dicstelen véget")
		g.OutTextXY(310, 350, "küldetésednek.")
		g.gameOverExit()
	}
	g.OutTextXY(310, 290, "Azonban hirtelen elfehérednek az")
	g.OutTextXY(310, 305, "ujjai. A gomb csütörtököt mond!")
	g.OutTextXY(310, 320, "Ajkáról lehervad a diadalmas vigyor.")
	g.OutTextXY(310, 335, "Egyre inkább a berregö fürészt figyeli")
	g.OutTextXY(310, 350, "a kezedben.")
	g.FlushKeys()
	g.WaitKey()
	g.showRoomPic("suli262.pic")
	g.clearTextWin()
	g.resetViewPort()
	g.OutTextXY(310, 170, "- Ne! Neee! Kegyelem! - könyörög, de")
	g.OutTextXY(310, 185, "hiába. Nem érdemel mást.")
	g.OutTextXY(310, 200, "- Ég veled, Edömér! - kiáltod, és")
	g.OutTextXY(310, 215, "meglendíted a szerszámot. Az acél")
	g.OutTextXY(310, 230, "fröcsögve, hersegve szeli a húsát,")
	g.OutTextXY(310, 245, "élvezettel meríted bele újra, és újra,")
	g.OutTextXY(310, 260, "mígnem csak egy felismerhetetlenségig")
	g.OutTextXY(310, 275, "összeroncsolt maradványhalom marad")
	g.OutTextXY(310, 290, "csupán az egykori zsarnokból, Kolompai")
	g.OutTextXY(310, 305, "Edömérböl. Igen. Küldetésedet siker")
	g.OutTextXY(310, 320, "koronázta.")
	g.FlushKeys()
	g.WaitKey()
	g.fadeOutLoadPal(10, "data\\rgb.col")
	g.endSequence()
	g.Delay(1000)
	g.CloseGraph()
	g.writeln(g.Output)
	g.write(g.Output, "  Tomcat Software Incorporated:                          140-05-98, Budapest  ")
	g.writeln(g.Output)
	g.writeln(g.Output)
	g.Halt()
}
